// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDc0JWSVgwr-nqPTJLW8aKnV25UOMN4Z6M',
    appId: '1:1046765374772:web:27a27cf1d852fa770da961',
    messagingSenderId: '1046765374772',
    projectId: 'todolist-1017',
    authDomain: 'todolist-1017.firebaseapp.com',
    storageBucket: 'todolist-1017.firebasestorage.app',
    measurementId: 'G-1GHSV2PXMJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxfD7uvdDwCoRV2weXAgS0qiFe7Sji-5U',
    appId: '1:1046765374772:android:0505cec9ea9ed7a00da961',
    messagingSenderId: '1046765374772',
    projectId: 'todolist-1017',
    storageBucket: 'todolist-1017.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlhL97j9jhu_vlCZDu3nVkHkX1QkmPJ0g',
    appId: '1:1046765374772:ios:a2bb26e189d2917d0da961',
    messagingSenderId: '1046765374772',
    projectId: 'todolist-1017',
    storageBucket: 'todolist-1017.firebasestorage.app',
    iosBundleId: 'com.example.toDolist',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAlhL97j9jhu_vlCZDu3nVkHkX1QkmPJ0g',
    appId: '1:1046765374772:ios:a2bb26e189d2917d0da961',
    messagingSenderId: '1046765374772',
    projectId: 'todolist-1017',
    storageBucket: 'todolist-1017.firebasestorage.app',
    iosBundleId: 'com.example.toDolist',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDc0JWSVgwr-nqPTJLW8aKnV25UOMN4Z6M',
    appId: '1:1046765374772:web:f96e4cf2ed7cec350da961',
    messagingSenderId: '1046765374772',
    projectId: 'todolist-1017',
    authDomain: 'todolist-1017.firebaseapp.com',
    storageBucket: 'todolist-1017.firebasestorage.app',
    measurementId: 'G-FYM1V6ED39',
  );
}
